### ISSUE TITLE
Multi-arch docker build

### ISSUE THREAD

**Issue by ipedrazas** [tinygo-org/docker#14]
Would you be interested in a PR to create multi-arch Docker images?

From the user's point of view, the docker image it's the same but Docker will pull the one that the host needs.

You can see what multi-arch Docker builds look like here:

![Screenshot 2022-07-19 at 12 06 44](https://user-images.githubusercontent.com/32796/179736192-b2f14ea5-aa57-4fa5-90ff-43276614a76e.png)

Changes are very simple: a couple of args in the Dockerfile and a couple of entries in the build.yml

**Comment by deadprogram** [comment]
That sounds really interesting!

Also worth mentioning, now that the tinygo executable is static build on Alpine, seems like the tinygo docker images could be based on Alpine to make them a lot smaller.

**Comment by deadprogram** [comment]
@ipedrazas did you ever have a chance to work on this?

**Comment by ipedrazas** [comment]
Yes! Sorry, the famous Spanish August break caught me :) I'll push the
changes later this week 🙌

**Comment by deadprogram** [comment]
Thanks!

**Comment by JohnniDi** [comment]
Since there are no other open issues, can we get a release number for this?

**Comment by deadprogram** [comment]
We will tag on next release @JohnniDi

**Comment by JohnniDi** [comment]
Is there a timeframe for the next release?

**Comment by deadprogram** [comment]
This month sometime, I think.

**Comment by deadprogram** [comment]
This was released, so now closing. Thanks @ipedrazas
