### ISSUE TITLE
Missing some package from build-essential

### ISSUE THREAD

**Issue by JohnniDi** [tinygo-org/docker#20]
Merging issue #19 into this one since the have the same root cause and potentially the same fix:

When running tests ("go test -tags=proxytest -test.v ./...") I get this error with v0.26.0, with v0.25.0 it works fine.

github.com/tetratelabs/proxy-wasm-go-sdk@v0.19.0: Get "https://proxy.golang.org/github.com/tetratelabs/proxy-wasm-go-sdk/@v/v0.19.0.zip": x509: certificate signed by unknown authority

Same error when compiling with "tinygo build -o aop-api-proxy.wasm -scheduler=none -no-debug -target=wasi ."

Testing v0.25.0 under user tinygo works fine.

Maybe related to this?
https://stackoverflow.com/questions/64462922/docker-multi-stage-build-go-image-x509-certificate-signed-by-unknown-authorit

When compiling I get he following error:
"# runtime/cgo _cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory     
3 | #include <stdlib.h>"

The error goes away after apt-get install build-essential
So, one of all those packages provides the correct stdlib.h

Potentially related to #19 as build-essential includes some ca-cert packages. => maybe --no-install-recommends is the culprit?

Successfully tested my theory with this
code: https://github.com/JohnniDi/tinygo
build: https://github.com/JohnniDi/tinygo/actions/runs/3219699676/jobs/5265417793
artifact: https://hub.docker.com/layers/flimburg/tinygo/master/images/sha256-ff6d7613506e4d9dd37d8a12db0cf533229c515ef788123b8359874ee9c1454b?context=repo
=> Requesting to remove --no-install-recommends from apt-get install from Dockerfile
Created a Pull Request

**Comment by deadprogram** [comment]
Closing this issues since it seems it was resolved. Thanks!
