### ISSUE TITLE
Add tinygo user to sudo group

### ISSUE THREAD

**Issue by jrauschenbusch** [tinygo-org/docker#22]
With the change to a non-root user in v0.26 there is no way to install further packages via aptitude.

```sh
$ apt-get install make
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

```sh
$ sudo apt-get install make
/bin/sh: 46: sudo: not found
```

**Comment by jrauschenbusch** [comment]
@deadprogram Could you please do a release? Would help me a lot!

**Comment by JohnniDi** [comment]
Yeah, a release for the current master state would be awesome.
While not this ticket we are waiting for something else and the corresponding ticket on my issue board starts to annoy me.

**Comment by jrauschenbusch** [comment]
@deadprogram Still waiting for a release. Would be really helpful. Otherwise i have to fork the repo.

**Comment by JohnniDi** [comment]
In case you have workaround that includes installing git take note that the recent security patch  http://security.debian.org/debian-security stable-security/main amd64 git amd64 1:2.30.2-1+deb11u1 [5514 kB] has issues with VCS stamping:
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.

**Comment by deadprogram** [comment]
).27.0 has been released. Now closing.
