### ISSUE TITLE
Unable to use container in GitHub Action because of file permissions

### ISSUE THREAD

**Issue by skirsten** [tinygo-org/docker#23]
So I am trying to use this container image in a GitHub Action (locally this works fine):

```sh
docker run --rm \
  -v $(pwd):/src \
  --workdir /src \
  tinygo/tinygo:master \
  tinygo build -o test.wasm -scheduler=none -target=wasi .
```

this result in `error: open test.wasm: permission denied`. So i tried to overwrite the user inside the container using `--user` but that did not work either:

```sh
docker run --rm \
  -v $(pwd):/src \
  --workdir /src \
  --user $(id -u):$(id -g) \
  tinygo/tinygo:master \
  tinygo build -o test.wasm -scheduler=none -target=wasi .
```
which results in `error: mkdir /.cache: permission denied`.

I was able to reproduce it locally by switching to the root user:
```sh
sudo -s
cd `mktemp -d`
cp -r old-src .
docker run ...
```

Any ideas how to circumvent this and help is appreciated.

**Comment by deadprogram** [comment]
I think this should be fixed by https://github.com/tinygo-org/docker/pull/24

**Comment by deadprogram** [comment]
0.27.0 has been released. Can you check to see if you still have this problem?

**Comment by deadprogram** [comment]
CLosing, since it appears to have been corrected. Please reopen if needed.
