### ISSUE TITLE
Builds using docker image currently fail: "could not read version from GOROOT"

### ISSUE THREAD

**Issue by quorauk** [tinygo-org/docker#3]
pulling the tinygo-zoo repo and running:

```sh
$ make build-arduino-colorlamp
```

results in
```sh
docker run --rm -v "/home/max/src/github.com/tinygo/tinygo-zoo:/src" -v "/home/max:/gohost" -e "GOPATH=/home/max:/gohost" tinygo/tinygo tinygo build -o /src/build/arduino-colorlamp.hex -target arduino /src/arduino-colorlamp/main.go
error: could not read version from GOROOT: /usr/local/go
make: *** [Makefile:10: build-arduino-colorlamp] Error 1
```

is GOROOT a required/new environment variable that the image does not provide?

**Comment by quorauk** [comment]
tinygo-zoo is using tinygo/tinygo:latest,

modifying it to use tinygo/tinygo:0.0.5 does work. I assume something changed between versions.

**Comment by deadprogram** [comment]
I call on @aykevl for assistance here, please...

**Comment by aykevl** [comment]
The error here is pretty confusing and doesn't say much. It means that something went wrong while reading `$GOROOT/VERSION` which in this case is /usr/local/go/VERSION.

**Comment by aykevl** [comment]
This should make the error clearer:
https://github.com/tinygo-org/tinygo/pull/395

In the meantime, you can check whether /usr/local/go/VERSION exists.

**Comment by deadprogram** [comment]
The reason for this error is that the zoo make tasks perform the "trick" of mounting the user's local Go install packages so that the docker image can find them.

This is not really docker image file related, should probably be reopened in the tinygo-zoo repo which is in need of several other updates as well.

**Comment by quorauk** [comment]
the file doesn't exist in the container no.

modifying the makefile to 

```
build-arduino-colorlamp:
    docker run --rm -v "$(PWD):/src" -v "$(GOPATH):/gohost" -e "GOPATH=$(GOPATH):/gohost" tinygo/tinygo bash -c "echo go1.12.6 > /usr/local/go/VERSION && tinygo build -o /src/build/arduino-colorlamp.hex -target arduino /src/arduino-colorlamp/main.go"
```

gives the same result I got with tinygo/tinygo:0.5.0.

I guess just adding that file into the image would potentially be a fix.

**Comment by deadprogram** [comment]
That might also make that error "go away". However, there are several other reasons why that make task will fail on the latest TinyGo anyhow.

**Comment by quorauk** [comment]
with my limited knowledge of how this works it might still be an issue in the docker image itself, here is a small example

test-script.sh
```sh
set -v
echo '
package main

import "fmt"

func main() {
  fmt.Println("hello world")
}
' > main.go
tinygo build -o main main.go
echo "go1.12.6" > /usr/local/go/VERSION
tinygo build -o main main.go
```

running `docker run -it -v $(pwd)/test-script.sh:/test-script.sh tinygo/tinygo bash test-script.sh` outputs

```
echo '
package main

import "fmt"

func main() {
  fmt.Println("hello world")
}
' > main.go
tinygo build -o main main.go
error: could not read version from GOROOT: /usr/local/go
echo "go1.12.6" > /usr/local/go/VERSION
tinygo build -o main main.g
```

**Comment by deadprogram** [comment]
Confirmed that it had the expected effect. Had to fix all of the tinygo zoo examples to match the tinygo 0.6.0 changes to do so.

Thanks for the fix, @quorauk much appreciated.
