### ISSUE TITLE
Tag 0.13.0 does not exist

### ISSUE THREAD

**Issue by codyoss** [tinygo-org/docker#9]
Looking through "Getting Started" -> "Docker":

- Ran: `docker pull tinygo/tinygo:0.13.0`
- Output: `Error response from daemon: manifest for tinygo/tinygo:0.13.0 not found`

Looking on dockerhub it seems like there was an update 5 days ago when the new version came out, but it was not tagged `0.13.0`.

**Comment by deadprogram** [comment]
Thanks for pointing that out @codyoss I have now pushed that tag.

Closing, thanks again!
